[package]
name = "test_plugin"
version = "0.1.0"
authors = ["marc2332 <mespinsanz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.86.0"
futures = "0.3.9"
orbtk = "0.3.1-alpha3"
json = "0.12.4"